### ISSUE TITLE
thoughts on resource-oriented sub-commands?

### ISSUE THREAD

**Issue by dweomer** [ibuildthecloud/k3c#11]
I realize that we are going for a throwback UX but one thing that I thought the Docker folks did really well over the last couple of years was re-organize the top-level sub-commands around the various resource types that one works with (while at the same time maintaining the legacy imperatives as top-level aliases). I really like the `k3c <noun> <verb>` formulation for establishing UX expectations.

**Comment by alexellis** [comment]
I never really adopted `docker container ls` vs `docker ps` and so forth, finding them rather verbose - when overdone, you get DigitalOcean's CLI `doctl compute cluster config save`. Interested to see what @ibuildthecloud thinks. What did Podman do out of curiosity?

**Comment by ibuildthecloud** [comment]
podman just copies everything from docker, so they implemented all the subcommands.  I very much do not like the <noun> <verb> construct if it can be avoided.  I know the CLI UX doesn't scale, but that also forces you to create small focused tools.  The bane of my existence is something like gcloud (and doctl does get an honorable mention).

**Comment by dweomer** [comment]
Looks like I don't have the votes!
