### ISSUE TITLE
Running k3c without root hangs

### ISSUE THREAD

**Issue by Waterdrips** [ibuildthecloud/k3c#5]
Im running `sudo ./k3c daemon` but keep missing out sudo on running the `k3c run`, `k3c ps` etc.

It wcould be great UX if k3c running without enough privileges could return an error, rather then hang forever.

**Comment by alexellis** [comment]
I got this too, an error would be good. Maybe like docker it needs a usermod to add a group?

**Comment by dweomer** [comment]
I am fairly certain that it is gRPC getting in the way: https://github.com/containerd/containerd/issues/2576
