### ISSUE TITLE
k3c = buildah?

### ISSUE THREAD

**Issue by gdha** [ibuildthecloud/k3c#9]
2 Questions:
1. is k3c functionality similar as the "buildah" one?
2. Can k3c work on the same node as k3s?

**Comment by warmchang** [comment]
As I understand:

- For traditional kubernetes distribution: k3c == containerd + buildkit + crictl
- For Redhat OCP 4: k3c == cri-o + podman (Contains buildah's build function) + crictl

**Comment by ibuildthecloud** [comment]
What @warmchang said is correct.  k3c and k3s should work fine on the same host.
